# Etapa 1: Construcción de la aplicación Angular
FROM node:18 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Compilar la aplicación Angular
RUN npm run build -- --project=administracionGastos --configuration production

# Etapa 2: Ejecutar la aplicación Angular compilada
FROM nginx:alpine

# Copiar los archivos compilados desde la etapa de construcción
COPY --from=build /app/dist/administracion-gastos /usr/share/nginx/html

# Copiar el archivo de configuración personalizado de Nginx
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto en el que se ejecuta la aplicación
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
