# Etapa 1: Construcción de la aplicación Angular
FROM node:20.12.2 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias utilizando npm
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Compilar la aplicación Angular para producción
RUN npm run build -- --configuration production

# Etapa 2: Servir la aplicación Angular compilada
FROM node:20.12.2

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos compilados desde la etapa de construcción
COPY --from=build /app/dist/administracion-gastos /app/dist/administracion-gastos

# Instalar un servidor HTTP simple para servir los archivos estáticos
RUN npm install -g http-server

# Exponer el puerto en el que se ejecuta la aplicación
EXPOSE 8080

# Comando para iniciar el servidor HTTP
CMD ["http-server", "dist/administracion-gastos", "-p", "8080"]
