# Usar una imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto que usa la aplicación (asumiendo que es el 3000)
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "server.js"]
